name = "git-lfs-s3-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"
workers_dev = false

routes = [
  { pattern = "github.limitbreak.com/*", zone_name = "limitbreak.com" }
]

[vars]
EXPIRY = "3600" 