name = "git-lfs-s3-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"
workers_dev = false
preview_urls = false

routes = [
  { pattern = "git-lfs.dev.limitbreak.com/*", zone_name = "dev.limitbreak.com" }
]

[vars]
EXPIRY = "3600" 